// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIllwlrUjhdaCNzS2MLRgJDz6T4B0bUuY',
    appId: '1:529245015711:web:8f5b742677451cc0c49caa',
    messagingSenderId: '529245015711',
    projectId: 'bustrack-342b4',
    authDomain: 'bustrack-342b4.firebaseapp.com',
    storageBucket: 'bustrack-342b4.appspot.com',
    measurementId: 'G-TQFG5QR85V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqWRF-nR_7GdzxsLaJDKeURl1BmTQxXo',
    appId: '1:529245015711:android:fe7f090aedf2fabdc49caa',
    messagingSenderId: '529245015711',
    projectId: 'bustrack-342b4',
    storageBucket: 'bustrack-342b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhds8Uo8xiAKSFtIrZwZfGKyf1pPXsHTE',
    appId: '1:529245015711:ios:b4b89aeb25296d24c49caa',
    messagingSenderId: '529245015711',
    projectId: 'bustrack-342b4',
    storageBucket: 'bustrack-342b4.appspot.com',
    iosBundleId: 'com.example.trialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhds8Uo8xiAKSFtIrZwZfGKyf1pPXsHTE',
    appId: '1:529245015711:ios:d009e9eca6d98a20c49caa',
    messagingSenderId: '529245015711',
    projectId: 'bustrack-342b4',
    storageBucket: 'bustrack-342b4.appspot.com',
    iosBundleId: 'com.example.trialapp.RunnerTests',
  );
}
